### PR TITLE
1d simulation g UI 657

### PR DESCRIPTION
**Pull request by ktbolt**
Add a couple of new meshing parameters and  coronary BC.

### CODE REVIEW

**Comment by mrp089** [comment]
I tested model ```0186_00002``` (coronary + RCR). I get the following error message:

```
[generate-1d-mesh] INFO - Parse arguments ...
[generate-1d-mesh] INFO - Centerlines input file: /home/pfaller/work/osmsc/data_generated/svprojects/0186_0002//test/centerlines.vtp
[generate-1d-mesh] INFO - Compute centerlines: False
[generate-1d-mesh] INFO - Density: 1.060000
[generate-1d-mesh] INFO - Element size: 0.100000
[generate-1d-mesh] INFO - Inflow input file: /home/pfaller/work/osmsc/data_generated/svprojects/0186_0002//test/inflow_3d.flow
[generate-1d-mesh] INFO - Linear material parameter Er/h: 10000000.000000
[generate-1d-mesh] INFO - Linear material parameter pressure: 0.000000
[generate-1d-mesh] INFO - Material model: LINEAR
[generate-1d-mesh] INFO - Minimum number of finite elements per segment: 10
[generate-1d-mesh] INFO - Model name: 0186_0002
[generate-1d-mesh] INFO - Number of time steps: 840
[generate-1d-mesh] INFO - Outflow bc file: /home/pfaller/work/osmsc/data_generated/svprojects/0186_0002//test
[generate-1d-mesh] INFO - Outflow bc type: ['cort.dat', 'rcrt.dat']
[generate-1d-mesh] INFO - Outlet face names file: '/home/pfaller/work/osmsc/data_generated/svprojects/0186_0002//test/outlet_face_names.dat'.
[generate-1d-mesh] INFO - Minimum number of sub-segments per master-segment: 1
[generate-1d-mesh] INFO - Sub-segment size in vessel master-segment: 9999
[generate-1d-mesh] INFO - Sub-segment size is adaptive: 0
[generate-1d-mesh] INFO - Save data frequency: 20
[generate-1d-mesh] INFO - Solver output file: solver.in
[generate-1d-mesh] INFO - Simulation time step: 0.001000
[generate-1d-mesh] INFO - Uniform boundary conditions: False
[generate-1d-mesh] INFO - Units: cm
[generate-1d-mesh] INFO - Viscosity: 0.040000
[generate-1d-mesh] INFO - Wall properties are uniform.
[generate-1d-mesh] INFO - Write mesh file: False
[generate-1d-mesh] INFO - Write solver file: True
[generate-1d-mesh] INFO - Read centerlines from the file: /home/pfaller/work/osmsc/data_generated/svprojects/0186_0002//test/centerlines.vtp
[generate-1d-mesh] INFO -    Number of points: 8174 
[generate-1d-mesh] INFO -    Number of cells: 8173 
[generate-1d-mesh] INFO -    Number of arrays: 0
[generate-1d-mesh] INFO - Generate the 1D mesh ...
[generate-1d-mesh] INFO - Read model outlet face names from: /home/pfaller/work/osmsc/data_generated/svprojects/0186_0002//test/outlet_face_names.dat
[generate-1d-mesh] INFO - Number of model outlet faces names: 10
[generate-1d-mesh] INFO - Outlet face names: ['rca_br1', 'rca_br2', 'rca_br3', 'aorta_outlet', 'lca_br1', 'lca_br2', 'lca_br3', 'lca_br4', 'lca_br5', 'lca_br6']
[generate-1d-mesh] INFO - Number of centerline branches: 17
[generate-1d-mesh] INFO - Number of centerline bifurcations: 7
[generate-1d-mesh] INFO - Number of svOneDSolver branches: 17
[generate-1d-mesh] INFO - Number of svOneDSolver joints: 7
[generate-1d-mesh] INFO - Set variable outflow boundary conditions ...
[generate-1d-mesh] ERROR - Error while reading variable outflow boundary conditions
[generate-1d-mesh] ERROR - Boundary condition file not found: /home/pfaller/work/osmsc/data_generated/svprojects/0186_0002//test/cort.dat
```

I [uploaded](https://drive.google.com/file/d/14i6brLRmMLwYHtC01rwEtoKkDw4hSn5D/view?usp=sharing) SV project. It looks like ```cort.dat``` and ```rcrt.dat``` were not written to the 1D project folder.

**Comment by mrp089** [comment]
Closes #657 (new meshing options) #740 (multiple BC types) #741 (coronary BCs)

**Comment by ktbolt** [comment]
@mrp089 I can't exactly say how this worked before, maybe I did the unthinkable and changed code without testing it ... 

Anyway,  the test you posted works. Please test some more.

**Comment by mrp089** [comment]
@ktbolt I'm still getting the same error (with the same 1D simulation and a fresh one). Might be that I'm doing something wrong?

Unrelated: #792 would make testing a little bit easier. But might be too many changes before the release...

**Comment by ktbolt** [comment]
When I run with the` 1d-simulation-GUI_657` branch SV prints
```
[generate-1d-mesh] INFO - Outflow bc type: ['cort.dat', 'rcrt.dat']
...
[generate-1d-mesh] INFO - Set variable outflow boundary conditions ...
[generate-1d-mesh] INFO - Surface rca_br2 boundary condition type coronary
[generate-1d-mesh] INFO - Surface rca_br1 boundary condition type coronary
[generate-1d-mesh] INFO - Surface lca_br4 boundary condition type coronary
[generate-1d-mesh] INFO - Surface aorta_outlet boundary condition type rcr
[generate-1d-mesh] INFO - Surface lca_br6 boundary condition type coronary
[generate-1d-mesh] INFO - Surface lca_br2 boundary condition type coronary
[generate-1d-mesh] INFO - Surface rca_br3 boundary condition type coronary
[generate-1d-mesh] INFO - Surface lca_br3 boundary condition type coronary
[generate-1d-mesh] INFO - Surface lca_br1 boundary condition type coronary
[generate-1d-mesh] INFO - Surface lca_br5 boundary condition type coronary
[generate-1d-mesh] INFO - Read inflow BC ...
[generate-1d-mesh] INFO - Write solver file.
[generate-1d-mesh] INFO - Write solver segment section ...
[generate-1d-mesh] INFO - Uniform BC: False
[generate-1d-mesh] INFO - Outflow BC: rcr
[generate-1d-mesh] INFO - Outflow BC: coronary
```
and in `0186_0002/Simulations1d/test` I see
```
centerlines.vtp		generate-1d-mesh.log	inlet_face_names.dat	outlet_face_names.dat	rcrt.dat
cort.dat		inflow_3d.flow		model_surface.vtp	parameters.npy		solver.in
```
It's silly to ask but did you pull and recompile?

**Comment by ktbolt** [comment]
@mrp089 #792 is a bit too complicated to add to this release and I am technically on vacation now.

**Comment by mrp089** [comment]
@ktbolt I did, but in the wrong folder... All good now!

**Comment by mrp089** [comment]
@ktbolt I thought this was done, but then I cloned a fresh repository, compiled, and tested again. The adaptive meshing doesn't work because SV-Python doesn't include ```scipy```. I don't know why this worked on my fork with an identical codebase (after manually including two packages in #796).

Is there a simple solution to this? If not, we have to remove the adaptive meshing button.

**Pull request merged**
