### PR TITLE
Simulation error handling. Issue 432

### PR DESCRIPTION
**Pull request by ktbolt**
I've added code to display the location of solver binaries, mpiexec binary and MPI implementation.

All of these are now being checked when creating a solver job, also added clearer error messages.

I also added some better error checking for solver jobs, now check exit code so failed jobs no longer appear to have completed ok.

### CODE REVIEW

**Comment by ktbolt** [comment]
@osmsc The builds with CMAKE=False are using Make to build? I did not update the Makefiles with my changes, I will do this.

**Comment by osmsc** [comment]
@ktbolt - yes, please add any new files to the makefiles.  I can fix anything "complicated", but if you just add a new class header and source file to cmake, please also add make at the same time.

**Comment by ktbolt** [comment]
@osmsc I updated the Makefile and all checks passed.

**Comment by ktbolt** [comment]
@osmsc Let's not merge this yet, some odd interaction going on with MITK database I need to understand.

**Comment by ktbolt** [comment]
@osmsc I added a check for Windows OS when getting the MPI implementation. The other functions had Windows-specific calls to the registry that I took from the original code.

**Pull request merged**
