### PR TITLE
[WIP] Update Make Build for New Adaptor Classes

### PR DESCRIPTION
**Pull request by osmsc**
I have updated the make build system to use Adam's new adaptor classes.  It builds the MeshSim adaptor as a shared object.

I also made additional changes required to compile on Windows.  In particular, the global variables (i.e. "...simvascular_globals...") needs to be a shared library on Windows since dll's can't see global variables in an .exe.

This code compiles and builds installers.  The parasolid-meshsim simple cylinder example runs, but the polydata-tetgen example crashes when parsing the meshing parameters string, and the discrete model complains about something not be implemented and then generates NaN simulation results.

The adaptor test script in SimVascular-Tests doesn't work for the parasolid-meshsim cylinder, but this appears to be an error in the script since it's referring to files that shouldn't exist (i.e. cylinder_results.vtu).

### CODE REVIEW

**Comment by updega2** [comment]
Okay, did you pull the latest version of the tests? I updated the tests in the new github tests repository later last week. They were working then. If so, I’ll take a look again to make sure they are working.

Thanks!

Adam

**Comment by osmsc** [comment]
Hi Adam,

I'm using the latest version of SimVascular-Test on github.

So I went back and made the make files let me link everything statically (commit to follow), and that seemed to solve the problem for steady_cylinder/discrete-meshsim.  This problem may have been due to global variables causing problems when I created shared libraries for simvascular_globals.

However, I still have problems running:

adapt_cylinder/parasolid-meshsim

The script crashes on the line:

"$adaptobject LoadMesh -file $vtu_mesh_file"

since the file:  

C:/cygwin64/home/nwilson/work/2015/2015-09-13-sv_tests_gitlab/tests/adapt_cylinder/parasolid-meshsim/09-14-2015-114713/cylinder_results.vtu

does not exist.  I don't see where this file would be generated at first glance in the test script.  Do you happen to have an old simulation result in the directory somehow?

As for steady_cylinder/polydata-tetgen, it appears to be crashing while parsing the command line options of "mymesh -options -values":

Here is the call stack when it seg faults:

> simvascular-vs12.5-ifort.exe!ARG_ParseTclListStatic(Tcl_Interp * interp, ARG_List_s list, ARG_Type_enum t, void * arr, int arrsz, int * numasn) Line 262	C++
> simvascular-vs12.5-ifort.exe!cvMesh_SetMeshOptionsMtd(void * clientData, Tcl_Interp * interp, int argc, const char * * argv) Line 1034	C++
 > simvascular-vs12.5-ifort.exe!cvMesh_ObjectCmd(void * clientData, Tcl_Interp * interp, int argc, const char * * argv) Line 324	C++

Nathan

**Comment by updega2** [comment]
Okay, cool, I'll test it out when I have the chance. 

Thanks! 

Adam

**Comment by osmsc** [comment]
Hi Adam,

The problem for "polydata-tetgen" is occurring when cvMesh_SetMeshOptionsMtd is being called with only the "-options" flag and the "-values" flag is missing.  In the cylinder.tgs created by the test script, the "NoBisect" doesn't have a value which is causing a memory access violation when the method tries to query the values.

Here is the cylinder.tgs as generated by the steady_cylinder test script for the polydata-tetgen example:

msinit
logon ./cylinder.logfile
loadModel ./cylinder.vtp
setSolidModel
newMesh
option surface 1
option volume 1
option GlobalEdgeSize 0.5
wallFaces wall
option QualityRatio 1.4
####  nate: this line works "option NoBisect 1"
option NoBisect
### nate: code never reaches here...
generateMesh
writeMesh ./cylinder.sms vtu 0
deleteMesh
deleteModel

You are specifying the "-values" as "GDSC_OPTIONAL", and then processing regardless in the code below:

static int cvMesh_SetMeshOptionsMtd( ClientData clientData, Tcl_Interp *interp,
				 int argc, CONST84 char *argv[] )
{
  cvMeshObject *geom = (cvMeshObject *)clientData;
  char *usage;
  char *flags;
  ARG_List valueList;

  int table_size = 2;
  ARG_Entry arg_table[] = {
    { "-options", STRING_Type   , &flags, NULL, REQUIRED, 0 , { 0 }},
    { "-values", LIST_Type   , &valueList, NULL, GDSC_OPTIONAL, 0 , { 0 }},
  };

  usage = ARG_GenSyntaxStr( 2, argv, table_size, arg_table );
  if ( argc == 2 ) {
    Tcl_SetResult( interp, usage, TCL_VOLATILE );
    return TCL_OK;
  }
  if ( ARG_ParseTclStr( interp, argc, argv, 2,
			table_size, arg_table ) != TCL_OK ) {
    Tcl_SetResult( interp, usage, TCL_VOLATILE );
    return TCL_ERROR;
  }

  double *values = new double [valueList.argc];
  int numValues = 0;
  if ( ARG_ParseTclListStatic( interp, valueList, DOUBLE_Type, values, valueList.argc, &numValues )
       != TCL_OK ) {
    Tcl_SetResult( interp, usage, TCL_VOLATILE );
    ARG_FreeListArgvs( table_size, arg_table );
    delete [] values;
    return TCL_ERROR;
  }

**Comment by updega2** [comment]
Okay, I will change it to a required  input. This runs fine on my mac and linux tests, which is why I didn’t catch it.
Thanks!

Adam

**Pull request closed without merging**
