### PR TITLE
Add Python API Docs

### PR DESCRIPTION
**Pull request by neilbalch**
Adds inline documentation to parts of the SimVascular Python API. Question marks indicate elements or attributes that I was unable to figure out the meaning for, and `TODO`s have been inserted in locations where the intentions of a particular syntactical block were unclear or appeared to be contradictory to the goal of the surrounding context.

### CODE REVIEW

**Comment by ktbolt** [comment]
@neilbalch This looks great, good detective work on what the arguments are used for.

**Comment by neilbalch** [comment]
This PR is now _mostly_ complete. I think the process of review should start soon. What do you think, @ktbolt?

**Comment by neilbalch** [comment]
Sorry about this dramatic shake-up of the commit history... I kindof screwed up the rebase on master accidentally.

**Comment by neilbalch** [comment]
Note: CI only fails because the time limit for builds expires. The code _does_ build.

**Comment by osmsc** [comment]
This is under development and doesn't need a pull request at this time.

**Comment by osmsc** [comment]
Closed.

**Comment by neilbalch** [comment]
@osmsc At what point should this be reopened? I can confirm that my contributions are complete now.

**Pull request closed without merging**
