### PR TITLE
Choose number of segments in 1D model-creation plugin

### PR DESCRIPTION
**Pull request by mrp089**
Let the user choose how many 1d segments should be created along a centerline vessel branch

Introduces three new parameters:
- min. number of sub-segments per vessel branch
- spacing of sub-segments
- option for adaptive spacing based on the change in cross-sectional area

Mesh refinement is handled in the Refinement class, based on the original one-segment-per-branch mesh.

Additional cleanup
- move i/o functions to a new file
- move i/o section headers to a new file
- formatting/ordering in mesh class

oneD

### CODE REVIEW

**Comment by ktbolt** [comment]
@mrp089 This looks very good! A couple of comments
1) SV does not support **scipy** so you will need to replace scipy functions with numpy calls
2) How can the mesh refinement fail or produce poor results or results that could cause the 1D solver to fail? Do you have checks for this?
3) Are there bounds for the input parameters? We don't want to create a 100 million element mesh!

**Comment by mrp089** [comment]
Thanks for your feedback @ktbolt!

> 1. SV does not support **scipy** so you will need to replace scipy functions with numpy calls

I removed scipy usage
> 2. How can the mesh refinement fail or produce poor results or results that could cause the 1D solver to fail? Do you have checks for this?

I added a lower and upper bound for the segment density. Adaptively placing the segments doesn't change the number of segments but only their distribution. This guarantees that the adaptive mesh doesn't become too crazy.
> 3. Are there bounds for the input parameters? We don't want to create a 100 million element mesh!

Since I don't know what users might choose as reasonable parameters, I think it's fine to have unbounded numbers of segments (as it is currently the case for the number of finite elements).

We could think about removing the number of finite elements as a parameter and let the user only control the number of segments (with a fixed number of finite elements per segment). @caseyfleeter, @melodydong, @wgyang do you think this makes sense?

**Comment by melodydong** [comment]
@mrp089 Letting the user only control the number of segments might make it easier from a user standpoint. My only concern is that if they specify too many segments, it will make the matrices to solve too large. @wgyang spent some time reducing the amount of segments in the PA tree because of this issue and can comment more on this. This might have just been an issue because of the extensiveness of the model, but it was taking an incredibly long time for the 1D solver to run on a PA tree.

**Comment by mrp089** [comment]
I completely restructured the centerline generation and the 1D-3D pipeline. I'll summarize below what I changed and why.

**New centerline generation**

pipeline
The centerline generation now works as follows (mostly implemented in `vtkvmtkPolyDataCenterlineSections.cxx`):
- Generate the centerline from the surface geometry using VMTK (don't apply branch splitting).
- Create a single connected centerline with line cells (`n` cells, `n+1` points). This avoids VMTK's issue of overlapping duplicate points and cells. For geometries with many outlets, this reduces the number of points significantly (e.g. factor 20 for pulmonary models) and speeds up all subsequent operations.
- Post-process the centerline by smoothing with a moving average filter globally and locally at the outlets to remove any "wiggles".
- Slice the surface geometry at all centerline points and calculate the cross-sectional area. This is based on [vmtkcenterlinesections](http://www.vmtk.org/vmtkscripts/vmtkcenterlinesections.html).
- Separate centerline in branches in bifurcations. This is crucial since the cross-sectional area in bifurcation regions is not well-defined. Bifurcations are defined where a slice cuts through more than one branch surface. This uses a "quick and dirty" coloring of the surface according to branches, similar to [vmtkbranchextractor](http://www.vmtk.org/tutorials/BranchSplitting.html).
- Generate the point arrays `BranchId` and `BifurcationId` to enumerate all branches and bifurcations, respectively. This numbering scheme replaces the [VMTK arrays](http://www.vmtk.org/vmtkscripts/vmtkbranchextractor.html) `GroupIds`, `CenterlineIds`, `TractIds`, `Blanking` and is much easier to handle.

**New svOneDSolver input file generation**

oned_refinement
The new 3D-1D pipeline now has the following features:
- The pipeline uses the `BranchId` and `BifurcationId` arrays, which is more straightforward than using the VMTK-provided arrays.
- The area is taken from the `CenterlineSectionsArea` and actually resembles the cross-sectional area of the 3D geometry.
- The bifurcations are entirely excluded from the computation. This allows better comparison to 3D models and enables flow models of bifurcations in the future.
- The user can choose the number of segments per branch. This resolves high changes in the cross-sectional area along a branch better. If desired, this can be based on adaptive meshing to optimally resolve the change in cross-sectional area with a given number of segments per branch.

**Next steps**
@ktbolt I need your help with connecting the new pipeline to the SimVascular GUI:

- [ ] Allow the user to select: number of segments per branch, minimum segment length, adaptive meshing (yes/no)
- [ ] Allow different boundary conditions in the same model (e.g. coronary and RCR) and pass to the 3D-1D pipeline
- [ ] Some cool visualization tools (1D model, cross-sectional area,  ...)

Also, I'd be happy if you could have a look at my code, especially at `vtkvmtkPolyDataCenterlineSections.cxx`. Thanks a lot!

**Comment by caseyfleeter** [comment]
@mrp089 this looks great to me!! Just checking - is there still a command line option? Or can this only be run through the gui?

**Comment by ktbolt** [comment]
@mrp089 Most excellent! 

This is too much detail for a pull request though. This information should be in a GitHub Issue so it can be tracked there, commented on, etc.

**Comment by mrp089** [comment]
> @mrp089 this looks great to me!! Just checking - is there still a command line option? Or can this only be run through the gui?

@caseyfleeter Yes! This functionality remains.

> @mrp089 Most excellent!
> 
> This is too much detail for a pull request though. This information should be in a GitHub Issue so it can be tracked there, commented on, etc.

@ktbolt Thanks! I opened issue #655 to document the changes (and old behavior).

I'll fix the travis build errors.

**Pull request merged**
