### PR TITLE
Fix to dicom vti issues

### PR DESCRIPTION
**Pull request by gmaher**
This PR fixes the issue where if you load a dicom and convert it to .vti, the views are all changed the next time you reload the project.

The fix stores the initial indexToWorldTransform matrix when the dicom is first loaded. When reloading the project, SimVascular will look for the transform file and set the reloaded image's transform to be what was in the file.

Tested this with OSMSC0110 dicom from the sv website and with Stephanies dicom, fixed in both cases. But could probably use more test cases.

To test:
* Create project
* load dicom image
* Convert to .vti
* Create a path with a few points
* Save and close project
* Reopen
* Check if all views still the same, path in correct location

### CODE REVIEW

**Comment by ktbolt** [comment]
@gmaher Please comment the code better, add why the transform file is needed. Do we need to print a message if the transform file is not present? Does the transform work correctly if the user scales the image?

**Comment by ktbolt** [comment]
Comments look great!

You may want use a standard file format like CSV to store the transformation, can add comments to the top of the file using "#".

I think we will discuss this during our Friday meeting.

**Comment by gmaher** [comment]
Converted the transform to xml and updated the SimVascular project number to 1.1.

Tested with various dicoms and creating new projects on Ubuntu 16, everything looks like it's working.

**Comment by ktbolt** [comment]
Looks good!

**Pull request merged**
