### PR TITLE
2016 06 26 switch python

### PR DESCRIPTION
**Pull request by osmsc**
Update to make system to build as either all shared libs or all static libs (tested on Windows)

cleanup in UI directory, legacy tcl directory, and itk level set segmentation directories (consolidated down to a single *_Init function to be called at runtime).

updated the cmake system build to work for developers build on Windows using SV16  (see test script in BuildWithMake/TestWithCMake)

### CODE REVIEW

**Comment by osmsc** [comment]
Adam - this is a pretty big commit (203 files changed) given that every function and class needed to have dllimport or dllexport in front of it on Windows

I haven't tested the changes on Linux/Mac or with "superbuild" (but it does work for a static & dynamic build on Windows, cmake static build)

**Comment by updega2** [comment]
Okay, I'll try to build it when I have the chance, but it looks like it failed on travis.

**Comment by updega2** [comment]
Looks like everything is compiling fine on mac and linux. It is just the startup script that needs to be changed it looks like.

**Comment by osmsc** [comment]
Thanks for checking.  Can you fix the startup script?  Can we merge this pull request and then you can do a quick follow along patch to the startup script for linux and mac?

**Comment by updega2** [comment]
Yea, I think that is probably the easiest.

**Pull request merged**
