### PR TITLE
Add interface to new svzerod solver 1034

### PR DESCRIPTION
**Pull request by ktbolt**
I've modified the SV ROM Simulation code to execute the new svzerod solver binary rather than the previous Python package (https://github.com/SimVascular/SimVascular/issues/1034).

### CODE REVIEW

**Comment by mrp089** [comment]
I can't test this pull request. SimVacular doesn't build on my Apple Silicon Mac, and I can't download the automatically built executable because `build-macos-big-sur` has been broken since 4aaf0c14f72528fcf8f46320c15b9c582aa37fbc.

Looking at the code: How is the `svZeroDPlus` executable included in SimVascular?

**Comment by mrp089** [comment]
@ktbolt, it seems like you deleted the [template](https://github.com/SimVascular/.github/blob/main/.github/pull_request_template.md) from this pull request. I think it would set a good example to start using it.

If you have constructive feedback for the templates, please open an issue [here](https://github.com/SimVascular/.github/issues).

**Comment by mrp089** [comment]
@ktbolt, I have my Ubuntu machine set up again and can open the GUI. Can you upload a Demo project so I can test this?

**Comment by ktbolt** [comment]
@mrp089 Sorry, upload a Demo project where? And which Demo project, from here https://simtk.org/frs/?group_id=930 ?

**Comment by mrp089** [comment]
Some (minimal) `SimVascular` project containing a 0D simulation, so I can test running `0D+` from `SimVascular`. Whatever you used to test your implementation is fine!

**Review by mrp089 — COMMENTED** [review]
@ktbolt, SimVascular executes `0D+` as expected :+1: 

However, it worked only after these steps:
- Download an installer for `0D+`
- Install `0D+`
- Manually set the executable path from `not found` to `/usr/local/sv/...` in SimVascular

Do we expect users to perform these steps themselves for running a `0D` simulation?

**Comment by ktbolt** [comment]
@mrp089 The first two steps are required. When I tested SV automatically set the path to the executable. Let me have a look, maybe something going on with the MITK database.

**Comment by ktbolt** [comment]
The SV Preferences is looking for `/usr/local/sv/ZeroDSolver`, which is what I tested, but the svZeroDPlus installer is storing svZeroDPlus binaries in `/usr/local/sv/svZeroDPlus`. 

We need to modify the svZeroDPlus installer to store binaries in`/usr/local/sv/ZeroDSolver` .

**Comment by mrp089** [comment]
I changed the binary folder in https://github.com/StanfordCBCL/svZeroDPlus/pull/62

@ktbolt, I understand that you want the 0D solver to be consistent with 3D and 1D. I'm still having a hard time accepting why we want users to go through the steps of finding, downloading, and installing software that we could ship with our Python packages (like we did for the Python-based 0D solver).

**Comment by ktbolt** [comment]
@mrp089 I agree that not needing to download the 0D solver is convenient for users. But 

Here are a few reasons not to include the 0D solver in the SV build
- Provides more flexibility, the solver can be upgraded without us having to build a new version of SV that a user would then need to re-install.
- Increases the dependences (complexity?) of the SV build, would need to install the 0D libraries and such 
- Perhaps problems on Windows, the current 0D solver Python version can't be loaded on Windows

I believe users know where to download the solvers. We need make sure this is documented. I've also added download instructions in the error message displayed when the 0D solver is not found.

**Comment by mrp089** [comment]
Checked with changes to install dir in https://github.com/StanfordCBCL/svZeroDPlus/pull/62 - works!

**Pull request merged**
