### PR TITLE
Level sets do not currently work on Windows so disable the 'LevelSet'…

### PR DESCRIPTION
**Pull request by ktbolt**
… button.

### CODE REVIEW

**Comment by osmsc** [comment]
@ktbolt - Dave - I want to hold off on this.  I have built the latest externals with mitk-2018.04.2 and itk-14.3.2 and the Windows level set bug appears to have disappeared.  Let's discuss on the software call.

**Comment by ktbolt** [comment]
@osmsc Excellent! I would like to try the new externals to see if they fix the DICOM read problem.

**Comment by osmsc** [comment]
@ktbolt - great minds must think a like.  I  just finished building the externals on Ubuntu 18 and the pulmonary data loaded in no problem.  So based on testing of N=1, yes this problem is fixed also :)  Of course, it takes 3+ hours to compile the externals on each platform so that slows things down a bit.  Trying to make the new externals available by tomorrow, depends on how things go on Mac.

**Comment by osmsc** [comment]
Level set works on Windows now.

**Pull request closed without merging**
