### PR TITLE
fix bug about flowsolver building on linux clusters with mpi

### PR DESCRIPTION
**Pull request by lanhzwind**

### CODE REVIEW

**Comment by ellipsis14** [comment]
Hi @lanhzwind @gmaher @updega2 @vsoch 
Does anyone of you has shell script to install svSolver on linux cluster with gcc compiler. I tried to install it but the effort went in vain. I was following this link https://github.com/lanhzwind/svSolver-on-Clusters.
Any suggestions and help shall be appreciated.

**Comment by vsoch** [comment]
The suggested approach I would take is to build it into a container, then pull with Singularity. Installing it specific to any cluster architecture is a huge effort that can be done once (with containers) and then extended to anywhere with Singularity (or Docker) installed.

**Comment by ellipsis14** [comment]
> The suggested approach I would take is to build it into a container, then pull with Singularity. Installing it specific to any cluster architecture is a huge effort that can be done once (with containers) and then extended to anywhere with Singularity (or Docker) installed.
@vsoch do you have the detailed instructions written anywhere ? How will I get the singularity image ?

**Comment by vsoch** [comment]
I suggested this and did the work in 2018 but it wasn’t wanted by the maintainers here. I don’t want to ruffle any feathers so I will let them address your question. Here is the PR that was closed: https://github.com/SimVascular/SimVascular/issues/368. If you want me to come back and make a second attempt, would be happy to.

**Comment by ellipsis14** [comment]
> I suggested this and did the work in 2018 but it wasn’t wanted by the maintainers here. I don’t want to ruffle any feathers so I will let them address your question. Here is the PR that was closed: #368. If you want me to come back and make a second attempt, would be happy to.
@vsoch Yes this is quite convenient approach without needing to install anything manually. Right now my main concern is to use mpi with svSolver on linux cluster where we do not have intel compiler. If you could come back and make a second attempt would be great.

**Comment by ktbolt** [comment]
@ellipsis14 Users running on a cluster build svSolver from source. See https://github.com/SimVascular/svSolver

Let's move this discussion to the SV Forum so other users can see it.

**Comment by ellipsis14** [comment]
@ktbolt What if I do not have the sudo privilege and cannot install MPICH on the cluster, however I can do module load openmpi/(specific version)

**Comment by ktbolt** [comment]
@ellipsis14 You just need to have the MPI libraries and headers installed so CMake can find them, **module load** will do that. You will need to load MPICH, not OpenMPI.

**Comment by ellipsis14** [comment]
@ktbolt I do not have MPICH module available. I am in europe now  and OpenMPI is quite popular on most clusters here not MPICH. Suggest me something that escapes MPICH otherwise I will have to do this bone breaking of configure and look for installing in local directory which is pain. The second option is I will have to ask the system admin to install MPICH on cluster.

**Comment by ktbolt** [comment]
@ellipsis14 Try with OpenMPI then. I've seen the build fail with OpenMPI on some platforms. What OS are you using? 

Also find out if people are using Docker / Singularity on the cluster. I don't think it would be too difficult to build a Docker container for svSolver, would be interesting to give it a try.

**Comment by vsoch** [comment]
Sounds good @ktbolt I'll redo the container build tomorrow! My previous PR was doing it from the binary, but it would be cleaner to install from source.

**Comment by alisonmarsden** [comment]
We probably just need the container build for svSolver, since this is the piece people use on a cluster.   I think last time you tried to create it for the entirety of SimVascular and that’s probably overkill.

**Comment by vsoch** [comment]
no worries @alisonmarsden I can give both a shot! We can develop a container for this use case, and if it's useful, I can create automated builds with different versions of MPI inside the container (this is the most important variable, the MPI in the container must match the host). I don't know a lot about SimVascular so I'm looking forward to giving it a spin :)

**Comment by vsoch** [comment]
heyo! So I have two containers built locally, one for svsolver and the other for simvascular. I'd like to make a grid of builds that have different installs of MPI (openmpi and impi you are using?) @ktbolt do you think you could give me a listing of the MPI libraries / versions that you'd like supported? And @ellipsis14 can you tell me the details for your cluster? I should be able to finish this up tomorrow, too pooped now.

**Comment by ellipsis14** [comment]
> @ellipsis14 Try with OpenMPI then. I've seen the build fail with OpenMPI on some platforms. What OS are you using?
> 
> Also find out if people are using Docker / Singularity on the cluster. I don't think it would be too difficult to build a Docker container for svSolver, would be interesting to give it a try.

@ktbolt Its centOS linux distribution

**Comment by ellipsis14** [comment]
> heyo! So I have two containers built locally, one for svsolver and the other for simvascular. I'd like to make a grid of builds that have different installs of MPI (openmpi and impi you are using?) @ktbolt do you think you could give me a listing of the MPI libraries / versions that you'd like supported? And @ellipsis14 can you tell me the details for your cluster? I should be able to finish this up tomorrow, too pooped now.

@vsoch Its cray machine and the containerization is available.

**Comment by vsoch** [comment]
heyo! Sorry about the delay -I had an issue that needed some triage this morning, and it took about an hour to fix up.

[Here](https://github.com/vsoch/simvascular) is the repository that has the Dockerfiles to build a container for each of svsolver and simvascular, both of which have OpenMPI version 1.10.7 installed (a bit old, yes, it's the one that I was testing in 2018). I haven't gotten a chance to test them myself yet because I badly need to go for a run before I continue working, but (after we get around tiny bugs) my suggestion for next steps is the following:

 - Can you point me to a good getting started guide that will provide basic sanity checks for using the tools so I can test both containers?
 - @ellipsis14 once we have a fully working container, likely the most important detail about your host is the flavor and version of MPI, if you would be able to share that.
 - then @ktbolt I think it would work well to do a CI setup that does a grid of builds across the various OS and MPI flavors / versions that are needed - we can have automated builds to Docker Hub, quay.io, Github container registry (or wherever you would prefer!) My preference is Quay.io because you can create robot tokens with repository-specific permissoins.
 - Let me know where you'd like the builds to happen, and I can either PR, or take the repository I've been developing and move under Simvascular to build from there. If the builds happen separately from the serving repos (svsolver and simvascular) e would want to discuss the appropriate trigger for a build.

Then it should be possible for a user, at any time, to pull the container that they need, e.g., I'm imagining a namespace like:

```bash
singularity pull docker://<organization>/simvascular:v<version>-openmpi-<version>
singularity pull docker://<organization>/simvascular:v<version>-mpich-<version>
```
And if OS is a factor as well, that would be included. Let me know your thoughts! I'm going on my run now to get out some energy but then I'll be around all day!

**Comment by vsoch** [comment]
Cool! So I was able to quickly pull and test the simvascular container and run it:

```bash
singularity pull docker://vanessa/simvascular
singularity run simvascular_latest.sif 
```

image

I can't say it fully works, but that's a good start! :D   Okay really going for a run this time :)

**Comment by ellipsis14** [comment]
@vsoch Many thanks for the effort!! My host has OpenMPI/3.1.4-GCC-8.3.0. I just need the container image for svSolver.

**Comment by vsoch** [comment]
okay! Let me do a quick manual build for that, that will be a good starting tester.

**Comment by vsoch** [comment]
okay I just pushed `vanessa/svsolver:openmpi-3.14`

The entrypoint is to a binary in /code/svSolver/BuildWithMake/Bin/svsolver-nompi.exe, and I want to point out some other files because I'm not sure that is the correct entrypoint (what is the correct way to build it to produce a binary _with_ mpi?) If you look in various places there are other executables that might be of interest, e.g.,

```
ls /code/svSolver/BuildWithMake/ext/bin/gnu/7.3/x64/release/vtk-8.1.1/bin/
vtkEncodeString-8.1  vtkHashSource-8.1

ls /code/svSolver/BuildWithMake/ext/bin/gnu/7.3/x64/release/vtk-8.1.1/    
bin/     include/ lib/     share/   

ls /code/svSolver/BuildWithMake/Bin/  
svpost-gcc-gfortran.exe  svpost.exe  svpre-gcc-gfortran.exe  svpre.exe  svsolver-gcc-gfortran-nompi.exe  svsolver-nompi.exe

ls /code/svSolver/BuildWithMake/    
Bin   MakeHelpers             README-build-macosx.txt   cluster_overrides.mk  include.mk  quick-build-linux.sh    sedscript
Docs  Makefile                README-build-windows.txt  ext                   mypost      quick-build-macosx.sh   targetlib.mk
Lib   README-build-linux.txt  Release                   global_overrides.mk   mypre       quick-build-windows.sh
```
The version of openmpi is 3.1.4, and you would need the matching libraries on your host. if you need to shell inside the Docker container you can do:

```bash
$ docker run --entrypoint bash -it vanessa/svsolver:openmpi-3.14 
```
And of course you should be able to pull like:

```bash
singularity pull docker://vanessa/svsolver:openmpi-3.14 
$ singularity run svsolver_openmpi-3.14.sif 

The process ID for myrank (0) is (3210).


The number of processes is 1.

Solver Input Files listed as below:
------------------------------------
 Local Config: solver.inp 
 Input file does not exist or is empty or perhaps you forgot mpirun? 
```
I've never used the solver before, so it could be that any of the following are true:

 1. we need to compile it differently to account for MPI (are there any libraries missing for example? Or are they provided on the host? Anything that needs to be added to LD_LIBRARY_PATH?
 2. there might be another executable that would be the correct entrypoint
 3. anything else!

If the entrypoint I chose is not correct, you can use a custom entrypoint via singularity exec, here are some examples:

```bash
$ singularity exec svsolver_openmpi-3.14.sif ls /code/svSolver/BuildWithMake/Bin/
svpost-gcc-gfortran.exe  svpost.exe  svpre-gcc-gfortran.exe  svpre.exe	svsolver-gcc-gfortran-nompi.exe  svsolver-nompi.exe

$ singularity exec svsolver_openmpi-3.14.sif /code/svSolver/BuildWithMake/Bin/svsolver-nompi.exe

The process ID for myrank (0) is (3379).


The number of processes is 1.

Solver Input Files listed as below:
------------------------------------
 Local Config: solver.inp 
 Input file does not exist or is empty or perhaps you forgot mpirun? 
```
It's not clear to me why the binaries end with .exe, which is normally a windows convention, but they don't appear to be for windows (this tripped me up at first!)

Let me know what you find when you test, and we'll go from there!

**Comment by vsoch** [comment]
And [here is the Dockerfile](https://github.com/vsoch/simvascular/blob/master/Dockerfile.svsolver-openmpi-3.14) if you want to take a look at the container guts.

**Comment by ellipsis14** [comment]
@vsoch just a quick question. what is the correct way to build it to produce a binary with mpi?.  I had no problem even building(without any containerization) from source with nompi on cluster . Anyway I will do little bone breaking tomorrow. Thank you for your effort.

**Comment by vsoch** [comment]
@ellipsis14 I don't know, I've never built it before, at least before last night! Can you point me to the instructions you used to build it and I can try to reproduce in the container? It could be that we need to add the MPI libraries to LD_LIBRARY_PATH (or some other method for the compilation to sniff that MPI is available).

**Comment by vsoch** [comment]
Let me try adding this before compile

```bash
export LD_LIBRARY_PATH=/usr/local/lib 
```
that seems to be where the binaries are.

**Comment by vsoch** [comment]
okay, rebuilding! I'll post an update after it's finished. I'm guessing that's the issue, that I was just silly and didn't have the libraries available when the compilation was looking for them. Sorry about that!

**Comment by vsoch** [comment]
@ellipsis14 still no MPI binary - can you do
```
env | grep MPI
```
and share the environment variables that are exported for when your MPI module is loaded? We can next try setting those. Then if that doesn't work we can ask for the help from maintainers here about what flags / envars are needed to compile with MPI support.

**Comment by vsoch** [comment]
Oh I think I just found it in include.mk, I guess this needs to be manually updated!
```
# -----------------------------------------------------
# Compile with MPI
# -----------------------------------------------------

SV_USE_MPI = 1
SV_USE_OPENMPI = 0
SV_USE_MPICH = 0

# by default, only build with real mpi on windows
ifeq ($(CLUSTER), x64_cygwin)
  SV_USE_DUMMY_MPI = 0
endif
ifeq ($(CLUSTER), x64_linux)
  SV_USE_DUMMY_MPI = 1
endif
ifeq ($(CLUSTER), x64_macosx)
  SV_USE_DUMMY_MPI = 1
endif
```

**Comment by vsoch** [comment]
This also looks like it's configured for Windows, but the quick-build-linux.sh creates a cluster override file to specify linux:

```
# default is windows, so override with gnu compilers and linux

echo "CLUSTER=x64_linux" > cluster_overrides.mk
echo "CXX_COMPILER_VERSION=gcc" >> cluster_overrides.mk
echo "FORTRAN_COMPILER_VERSION=gfortran" >> cluster_overrides.mk
echo "SV_COMPILER=gnu" >> cluster_overrides.mk
echo "SV_COMPILER_VERSION=$EXTERNALS_SV_COMPILER_VER_NO" >> cluster_overrides.mk
```
But I don't think that includes setting OPENMPI to 1 (enabled). That's probably it - I just need some trick to change that setting.

**Comment by vsoch** [comment]
okay I'm building again with a sed replace of that line to 1 (not the greatest method, but it will let us test if the correct binary is produced!) @ellipsis14 what other changes did you do to include.mk, other than the ones set in the quick-build-linux.sh?

**Comment by vsoch** [comment]
That didn't resolve it - here is the start of the compile output. Let's wait for feedback from @ktbolt and of course be respectful that this is a Sunday, and it's also coronapocalypse season so people really need the weekend days to relax!

```
5]

/code/svSolver/BuildWithMake
/code/svSolver/BuildWithMake/ext/bin/gnu/7.3/x64/release /code/svSolver/BuildWithMake
untar /code/svSolver/BuildWithMake/ext/tarfiles/ubuntu.18.04.gnu.7.3.x64.release.2019.11.16.vtk.8.1.1.tar.gz
/code/svSolver/BuildWithMake
make shared-pre-build static-build
make[1]: Entering directory '/code/svSolver/BuildWithMake'
if [ -e tclscript ];then /bin/rm -f tclscript;fi
if [ -e sedscript ];then /bin/rm -f sedscript;fi
if [ -e mysolver ];then /bin/rm -f mysolver;fi
echo "puts \"s+REPLACEME_SOFTWARE_PLATFORM+x64_linux+g\"" > tclscript 
echo "puts \"s+REPLACEME_CXX_COMPILER_VERSION+gcc+g\"" >> tclscript
echo "puts \"s+REPLACEME_FORTRAN_COMPILER_VERSION+gfortran+g\"" >> tclscript
echo "puts \"s+REPLACEME_SV_HOME+[file rootname `pwd`]/..+g\"" >> tclscript
echo "puts \"s+REPLACEME_SV_VERSION++g\"" >> tclscript
echo "puts \"s+REPLACEME_LIB_BUILD_DIR+x64_linux/gcc-gfortran+g\"" >> tclscript
echo "puts \"s+MPIEXEC++g\"" >> tclscript
echo "puts \"s+REPLACEME_SV_OS+linux+g\"" >> tclscript
echo "puts \"s+REPLACEME_OPEN_SOFTWARE_BINARIES_TOPLEVEL+/code/svSolver/BuildWithMake/ext/bin/gnu/7.3/x64/release+g\"" >> tclscript
echo "puts \"s+REPLACEME_LICENSED_SOFTWARE_TOPLEVEL++g\"" >> tclscript
echo "puts \"s+REPLACEME_MPI_SO_PATH++g\"" >> tclscript
echo "puts \"s+REPLACEME_MPIEXEC_PATH++g\"" >> tclscript
echo "puts \"s+REPLACEME_VTK_SO_PATH+/code/svSolver/BuildWithMake/ext/bin/gnu/7.3/x64/release/vtk-8.1.1/lib+g\"" >> tclscript
echo "puts \"s+REPLACEME_VTK_BIN_PATH+/code/svSolver/BuildWithMake/ext/bin/gnu/7.3/x64/release/vtk-8.1.1/bin+g\"" >> tclscript
echo "puts \"s+REPLACEME_VTK_LIB_PATH+/code/svSolver/BuildWithMake/ext/bin/gnu/7.3/x64/release/vtk-8.1.1/lib+g\"" >> tclscript
echo "puts \"s+REPLACEME_INTEL_COMPILER_SO_PATH++g\"" >> tclscript
echo "puts \"s+REPLACEME_MPI_NAME+nompi+g\"" >> tclscript
/usr/bin/tclsh tclscript > sedscript
/bin/sh: 1: /usr/bin/tclsh: not found
Makefile:49: recipe for target 'mksedscript' failed
rm -f tclscript
make[1]: [mksedscript] Error 127 (ignored)
mkdir -p ./../Code/FlowSolvers/Include/Make
sed -f sedscript ./Release/developer_wrapper_scripts/developer-core-script > mypre
sed -f sedscript ./Release/developer_wrapper_scripts/developer-core-script > mypost
sed -f sedscript ./Release/developer_wrapper_scripts/developer-svpre-script >> mypre
sed -f sedscript ./Release/developer_wrapper_scripts/developer-svpost-script >> mypost
chmod a+rx mypre
chmod a+rx mypost
chmod a+rx mysolver-nompi
chmod: cannot access 'mysolver-nompi': No such file or directory
make[1]: [post-build] Error 1 (ignored)
Makefile:159: recipe for target 'post-build' failed
chmod a+rx mysolver-nompi
chmod: cannot access 'mysolver-nompi': No such file or directory
Makefile:159: recipe for target 'post-build' failed
...
```

**Comment by vsoch** [comment]
@ellipsis14 can you show me the documentation you followed for building with cmake? I can try that same method, although cmake is a bit of a monster :P

**Comment by ellipsis14** [comment]
@vsoch Its this one https://github.com/SimVascular/svSolver, however you will have to be little careful about the gfortran and cmake version.

**Comment by vsoch** [comment]
Looks like I'm missing some MPI setting...
```
root@8e8fe443be8d:/code/svSolver/svSolver-build# cmake -DSV_USE_LOCAL_VTK=ON ..
CMake Deprecation Warning at CMakeLists.txt:51 (cmake_policy):
  The OLD behavior for policy CMP0025 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- SimVascular Version: simvascular 2020-04-06
-- Configuring done
-- Generating done
-- Build files have been written to: /code/svSolver/svSolver-build
root@8e8fe443be8d:/code/svSolver/svSolver-build# make
Scanning dependencies of target svSolver
[ 12%] Creating directories for 'svSolver'
[ 25%] No download step for 'svSolver'
[ 37%] No patch step for 'svSolver'
[ 50%] No update step for 'svSolver'
[ 62%] Performing configure step for 'svSolver'
loading initial cache file /code/svSolver/svSolver-build/svSolver-prefix/tmp/svSolver-cache-RelWithDebInfo.cmake
CMake Deprecation Warning at CMakeLists.txt:43 (cmake_policy):
  The OLD behavior for policy CMP0025 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- SimVascular Version: simvascular 2020-04-06
-- The Fortran compiler identification is GNU 7.5.0
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Warning at CMake/SimVascularMacros.cmake:92 (find_package):
  By not providing "FindVTK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "VTK", but
  CMake did not find one.

  Could not find a package configuration file provided by "VTK" with any of
  the following names:

    VTKConfig.cmake
    vtk-config.cmake

  Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
  to a directory containing one of the above files.  If "VTK" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMake/SimVascularExternals.cmake:38 (simvascular_external)
  CMakeLists.txt:106 (include)


CMake Error at CMake/SimVascularExternals.cmake:44 (include):
  include called with wrong number of arguments.  include() only takes one
  file.
Call Stack (most recent call first):
  CMakeLists.txt:106 (include)


-- Found MPI_C: /usr/local/lib/libmpi.so  
-- Found MPI_CXX: /usr/local/lib/libmpi.so  
-- Found MPI_Fortran: /usr/local/lib/libmpi_usempif08.so;/usr/local/lib/libmpi_usempi_ignore_tkr.so;/usr/local/lib/libmpi_mpifh.so;/usr/local/lib/libmpi.so  
-- PKG MPI found!
-- FlowSolvers
--     ThreeDSolver
--         ThreeDSolver Options
--             Activating coronary bc feature
--             Activating closed loop bc feature
--             Activating variable wall feature
--             Activating using VTK feature
--         ThreeDSolver Components
--             svLS
--             svPost
--             SolverIO
--             svPre
--             svSolver
-- Generating svpost scripts. Dev name: mypost, install name:  svpost
-- Generating svpre scripts. Dev name: mypre, install name:  svpre
-- Generating svsolver scripts. Dev name: mysolver, install name:  svsolver
-- Generating svsolver-nompi scripts. Dev name: mysolver-nompi, install name:  svsolver-nompi
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MPI_EXTRA_LIBRARY
    linked by target "_simvascular_threedsolver_write_restart" in directory /code/svSolver/Code/FlowSolvers/ThreeDSolver/svSolver
    linked by target "_simvascular_threedsolver_fortran" in directory /code/svSolver/Code/FlowSolvers/ThreeDSolver/svSolver
    linked by target "svsolver" in directory /code/svSolver/Code/FlowSolvers/ThreeDSolver/svSolver

-- Configuring incomplete, errors occurred!
See also "/code/svSolver/svSolver-build/svSolver-build/CMakeFiles/CMakeOutput.log".
CMakeFiles/svSolver.dir/build.make:105: recipe for target 'svSolver-prefix/src/svSolver-stamp/svSolver-configure' failed
make[2]: *** [svSolver-prefix/src/svSolver-stamp/svSolver-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/svSolver.dir/all' failed
make[1]: *** [CMakeFiles/svSolver.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
Why isn't there an automated build anywhere to show exactly how this is done? @ellipsis14 what do you have set for `MPI_EXTRA_LIBRARY`?

**Comment by ellipsis14** [comment]
@vsoch  which cmake version did you use ? I did not have to set any MPI_EXTRA_LIBRARY. The only problem I had was compiling with gfortran 8.3.0 which I removed after loading appropriate impi module. I used CMAKE/3.7.2-intel-2017b version of cmake. 
Now answering this question: "Why isn't there an automated build anywhere to show exactly how this is done?". Its the common problem I have noticed with open source is "the person who does the technical part (most of them I have found are arrogant and like self patting their back) does not write the documentation and the person who writes the documentation(mostly convoluted: legal language) does not implement the technical stuff
May be @ktbolt knows better how to fix your issue. I am new user to this solver so I will bug you all from time to time.

**Comment by ktbolt** [comment]
@ellipsis14 Your comment on open source developers is inappropriate. Please refrain from making such insulting generalizations about the open source community.

**Pull request merged**
