### PR TITLE
Add checking for extra newlines in a flow rate file. Also changed the…

### PR DESCRIPTION
**Pull request by ktbolt**
… error message for for segments where the inlet area is > outlet area to a warning.

This will fix the failures users are seeing on Windows.

### CODE REVIEW

**Comment by osmsc** [comment]
@ktbolt - Dave - can we change <prop key="Flow Rate" value="..."> in the .s1djb to not have newlines or carriage returns at all?  Embedding ";" or "x-0-A" in the .s1djb is odd to me.  This should just be a string of numbers with the format of t0 flow0 t1 flow1 t2 flow2 ...".  We could have an additional flag of the number of pairs if you want a data check.  Also, in Tcl I tend to write everything with just linefeeds as the line ending (this is done with fconfigure command in Tcl) since some things (e.g. meshsim) don't handle carriage returns well.  Do we have this option from Qt / MITK?  It seems like the .s1jb file has carriage returns at the end of all lines (i.e. dos-format).

**Comment by ktbolt** [comment]
@osmsc I can rewrite the way the plugin reads / writes flow rate data to the .s1djb file. The code currently reads in the file and stores it as a single string, I would just need to add a bit more processing. I hesitate slightly because I'm not exactly sure how the .s1djb file / job object / CapsBCWidget interact, had some problems with this trying to check the state of input data.

**Comment by osmsc** [comment]
@ktbolt - I think it would be better to process the file and build up a string to stick in the .s1dbg.  I would think this is pretty straightfoward as you could use fopen etc. from C++ (or simple python).  I think most of the readline functions in C++ handle different line endings fairly cleanly, although you could search replace carriage return in need be.

**Comment by ktbolt** [comment]
@osmsc I will make the Simulation1D code changes. The Simulation1D code was copied from the   Simulation plugin code so I will also make the same changes there.

**Pull request merged**
