### PR TITLE
Sv workbench

### PR DESCRIPTION
**Pull request by updega2**
Merge svWorkbench

### CODE REVIEW

**Comment by updega2** [comment]
Okay, this should be good to merge when we are ready. @osmsc 

A couple things you should be aware of:
I made the qt gui default now. We can change back and forth as needed. 
The cmake build will build and launch with mitk config specified.
The cmake build will build and launch but crash with mitk install dir specified. Still working out issue on mac. 
Everything is still messy on the cmake side. Once we get everything working, I will clean up.

**Comment by osmsc** [comment]
Let's merge.  I'm not sure about the Qt GUI being the default - we don't have a single image of documentation on our website etc.  In any case,  will merge and then we can debate on Friday!

**Comment by osmsc** [comment]
Should I wait until the travis build is done or just do it now?

**Comment by updega2** [comment]
Yea, its two line changes, so I figure not a big deal to change.

**Comment by updega2** [comment]
We can skip travis. I'll merge now and you can make your changes.

**Comment by osmsc** [comment]
ok

**Pull request merged**
