### PR TITLE
adding clear instruction to TWO different documentation bases

### PR DESCRIPTION
**Pull request by vsoch**
This would have saved me about 5-7 hours of stressful work today. I didn't even know there were two "installation options..."

### CODE REVIEW

**Comment by osmsc** [comment]
@ktbolt - are these the correct links?  Should we commit this?

**Comment by ktbolt** [comment]
@osmsc The links are correct so I guess we can commit this but I will be updating the README the next couple of weeks anyway.

@vsoch I'm not sure how all the confusion at the SRCC about what needed to be installed on Sherlock came about. I suppose they just said they wanted SimVascular installed implying that it was only the solver they wanted and not the modeling building app. The distinction between the different tools needs to be made clearer I think.

**Comment by vsoch** [comment]
Apart from Sherlock and which smaller tools might have been needed there, the larger issue is that this software is not easily reproducible on any linux flavor machine. See this issue here: https://github.com/SimVascular/SimVascular/issues/368 There needs to be a container based (Docker) version so that a user doesn't need to install / go through pages of instructions to get the software working. If the software is used for a publication, the researcher can reference the exact container version that was used, and anyone (across platforms) could then run it. We can continue this conversation in https://github.com/SimVascular/SimVascular/issues/368 since it's out of scope for this PR. Thanks!

**Comment by vsoch** [comment]
Hooray! :)

**Pull request merged**
